name: CI

on:
  push:
    branches: [main]

jobs:
  poetry-master:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f poetry-master.Dockerfile .

  poetry-with-fix:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f poetry-with-fix.Dockerfile .
